services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db

  app:
    image: weseek/growi:4.3.2
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/growi
      ELASTICSEARCH_URI: "http:/${ELASTICSEARCH_HOST}/growi"
      PASSWORD_SEED: changeme
    restart: unless-stopped
    volumes:
      - growi_data:/data

  https-portal:
    image: steveltn/https-portal:1
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "${DOMAIN} -> http://app:3000"
      STAGE: "${STAGE}"
      FORCE_RENEW: "false"
      WEBSOCKET: "true"
      CLIENT_MAX_BODY_SIZE: 0
    restart: unless-stopped
    volumes:
      - https-portal_data:/var/lib/https-portal

  minio:
    image: minio/minio:RELEASE.2021-07-27T02-40-15Z
    environment:
      MINIO_ROOT_USER: fakeMyKeyId
      MINIO_ROOT_PASSWORD: fakeSecretAccessKey
    restart: unless-stopped
    volumes:
      - "${BKUP_DIR}:/export"
    command: server /export

  backup:
    image: weseek/mongodb-awesome-backup:0.6.1
    depends_on:
      - minio
    environment:
      CRONMODE: "true"
      CRON_EXPRESSION: 0 4 * * *
      AWS_ACCESS_KEY_ID: fakeMyKeyId
      AWS_SECRET_ACCESS_KEY: fakeSecretAccessKey
      TARGET_BUCKET_URL: s3://growi/
      AWSCLI_ENDPOINT_OPT: http://minio:9000/
    restart: unless-stopped

volumes:
  growi_data:
  https-portal_data:
  mongo_configdb:
  mongo_db:
